- name: IdoKendo
  hosts: localhost
  connection: local
  vars:
    should_be_root: "{{ False if ansible_os_family == 'Darwin' else True }}"
  pre_tasks:
    - name: Update cache
      when: ansible_os_family != 'Darwin'
      become: "{{ should_be_root }}"
      apt:
        update_cache: true
      tags:
      - terminal
      - nvim
      - node
      - dotfiles
      - python
      - rust
      - fastfetch
  tasks:
  - include_tasks: tasks/coreutils.yml
  - include_tasks: tasks/terminal.yml
  - include_tasks: tasks/dotfiles.yml
  - include_tasks: tasks/node.yml
  - include_tasks: tasks/nvim.yml
  - include_tasks: tasks/python.yml
  - include_tasks: tasks/rust.yml
  - include_tasks: tasks/fastfetch.yml
