- name: stow is present
  package:
    name: stow
    state: present
  tags:
    - dotfiles
- name: fzf is present
  package:
    name: fzf
    state: present
  tags:
    - dotfiles
- name: github.com is a known host
  lineinfile:
    dest: $HOME/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
- name: dotfiles repo is cloned
  ansible.builtin.git:
    repo: git@github.com:IdoKendo/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
- name: dotfiles folders are stowed
  shell: cd $HOME/.dotfiles && for dir in */; do stow "$dir"; done
  tags:
    - dotfiles
