- name: Install Fastfetch dependencies
  become: true
  apt:
    name: ["cmake"]
  tags:
    - fastfetch
- name: Remove Fastfetch
  shell: rm -rf ~/fastfetch
  tags:
    - fastfetch
- name: Clone Fastfetch
  ansible.builtin.git:
    repo: https://github.com/fastfetch-cli/fastfetch.git
    dest: "{{ lookup('env', 'HOME') }}/fastfetch"
  tags:
    - fastfetch
- name: Build Fastfetch
  shell: "cd {{ lookup('env', 'HOME') }}/fastfetch && ./run.sh"
  tags:
    - fastfetch
