- name: Install NVM
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | sh
  tags:
    - node
- name: Add NVM to .bashrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion'
  tags:
    - node
