- name: Install Python dependencies
  become: true
  apt:
    name: ["build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "curl", "libncursesw5-dev", "xz-utils", "tk-dev", "libxml2-dev", "libxmlsec1-dev", "libffi-dev", "liblzma-dev"]
  tags:
    - python
- name: Install pyenv
  shell: curl https://pyenv.run | bash
  tags:
    - python
- name: Add pyenv to .bashrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
  tags:
    - python
